config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get 'profiles', to: 'users/registrations#new_profile'
    post 'profiles', to: 'users/registrations#create_profile'
  end
  root "home#index"
  resources :users, only: [:show, :edit, :update]
  resources :profiles, only: [:edit, :update]
  resources :posts do
    resources :comments, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
  
  validates_uniqueness_of :post_id, scope: :user_id
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_post

  def create
    @like = current_user.likes.create(post_id: params[:post_id])
  end

  def destroy
    @like = Like.find_by(post_id: params[:post_id], user_id: current_user.id)
    @like.destroy
  end

  def set_post
    @post = Post.find(params[:post_id])
  end
end

app/views/likes/_like.html.haml
- if current_user
  .Post-empathy
    %p.Post-empathy__text 共感
    - if current_user.already_liked?(post)
      = link_to post_like_path(post, current_user.likes.find_by(post_id: @post.id)), method: :delete, remote: true, class: "Post-empathy__link, Post-empathy__link--red" do
        = icon('fas', 'heart', class: 'Post-empathy__icon')
    - else
      = link_to post_likes_path(post), method: :post, remote: true, class: "Post-empathy__link, Post-empathy__link--gray" do
        = icon('fas', 'heart', class: 'Post-empathy__icon')
    %p.Post-empathy__number
      = post.likes.count

app/views/likes/create.js.erb
$("#like_<%= @post.id %>").html("<%= escape_javascript(render partial: "like", locals: { post: @post }) %>");

app/views/likes/destroy.js.erb
$("#like_<%= @post.id %>").html("<%= escape_javascript(render partial: "like", locals: { post: @post }) %>");