config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get 'profiles', to: 'users/registrations#new_profile'
    post 'profiles', to: 'users/registrations#create_profile'
  end
  root "home#index"
  resources :users, only: [:show, :edit, :update]
  resources :profiles, only: [:edit, :update]
  resources :posts do
    resources :comments, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_one :profile, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :comments
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post

  validates :last_name, :first_name, :last_name_kana, :first_name_kana, presence: true
  validates :last_name_kana, :first_name_kana, format: { with: /\A[ぁ-んー－]+\z/ }

  def already_liked?(post)
    self.likes.exists?(post_id: post.id)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    @user = User.new
  end

  # POST /resource
  def create
    @user = User.new(sign_up_params)
    unless @user.valid?
      flash.now[:alert] = @user.errors.full_messages
      render :new and return
    end
      session["devise.regist_data"] = {user: @user.attributes}
      session["devise.regist_data"][:user]["password"] = params[:user][:password]
      @profile = @user.build_profile
      render :new_profile
  end

  def create_profile
    @user = User.new(session["devise.regist_data"]["user"])
    @profile = Profile.new(profile_params)
    unless @profile.valid?
      flash.now[:alert] = @profile.errors.full_messages
      render :new_profile and return
    end
    @user.build_profile(@profile.attributes)
    @user.save
    session["devise.regist_data"]["user"].clear
    sign_in(:user, @user)
    redirect_to root_path, notice: '登録完了しました'
  end

  protected

  def profile_params
    params.require(:profile).permit(:nickname, :prefecture_id, :introduction, :image)
  end



  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.order('created_at DESC')
    @profile = @user.profile
  end

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path, notice: "ユーザー情報を更新しました"
    else
      render :edit
    end
  end

private

  def user_params
    params.require(:user).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :password)
  end

  def ensure_correct_user
    if current_user.id != params[:id].to_i
      redirect_to root_path, alert: '権限がありません'
    end
  end
end

app/views/users/_header.html.haml
.header-wrapper
  .Header
    %h1.Header__title
      =link_to "relife", root_path
    
    .Header__items
      - if user_signed_in?
        %p
          = @profile.nickname
        %p
          = link_to "マイページ", user_path(current_user.id)
        %p
          = link_to "ログアウト", destroy_user_session_path, method: :delete
      - else
        %p
          = link_to "新規登録", new_user_registration_path
        %p
          = link_to "ログイン", new_user_session_path

app/views/users/_post.html.haml
= link_to post_path(post.id) do
  .Mypost-item
    .Mypost-prof
      .Mypost-prof__name
        = post.user.profile.nickname
      .Mypost-prof__time
        = post.created_at.strftime("%Y/%m/%d %H:%M")
    .Mypost-item__title
      = post.title
    .Mypost-item__text
      = post.content
    .Mypost-item__empathy-count
      %p
        = post.liked_users.count
        %span
          人が共感しています

app/views/users/_profile.html.haml
.profile-info
  .Profile
    - if current_user.id == @user.id
      .Profile-edit
        = link_to edit_profile_path(@profile), class: "Profile-edit__link" do
          = icon('fas', 'cog', class: 'Profile-edit__icon')
    - if @profile.image.present?
      .Profile__main-image
        = image_tag @profile.image.url, class: "Profile__image"
    - else
      .Profile__main-image--empty
        画像なし
    .Profile__name
      = @profile.nickname
    - if @profile.prefecture_id.present?
      .Profile__area
        = @profile.prefecture.name
    - if @profile.introduction.present?
      .Profile__introduction
        = @profile.introduction

app/views/users/edit.html.haml
.User
  %h1
    =link_to "relief", root_path
    
  .User__wrapper
    %h2 ユーザー情報編集
    = form_with model: current_user, local: true do |f|
      - if current_user.errors.any?
        .edit-errors
          %ul
            - current_user.errors.full_messages.each do |user|
              %li= user
      
      .Name-form
        .Name-form__wrapper
          %ul.Name-form__field
            %li 名字
            %li.Name-form__required 必須
          = f.text_field :last_name, class: "Name-form__input"
        .Name-form__wrapper
          %ul.Name-form__field
            %li 名前
            %li.Name-form__required 必須
          = f.text_field :first_name, class: "Name-form__input"

      .Name-form
        .Name-form__wrapper
          %ul.Name-form__field
            %li 名字(かな)
            %li.Name-form__required 必須
          = f.text_field :last_name_kana, class: "Name-form__input"
        .Name-form__wrapper
          %ul.Name-form__field
            %li 名前(かな)
            %li.Name-form__required 必須
          = f.text_field :first_name_kana, class: "Name-form__input"

      .User-form
        %ul.User-form__field
          %li メールアドレス
          %li.User-form__required 必須
        = f.email_field :email, autofocus: true, autocomplete: "email", class: "User-form__input"

      .User-form
        %ul.User-form__field
          %li パスワード
          %li.User-form__required 必須
        = f.password_field :password, autocomplete: "new-password", placeholder: '6文字以上', class: "User-form__input"

      .Information.Information--right
        .Information__submit
          = f.submit "登 録 す る", class: "Information__submit--btn"

app/views/users/show.html.haml
= render "home/header"

.mypage-wrapper
  = render "profile"
  .mypost-wrapper
    .mypost-holder
      = render partial: "users/post", collection: @posts