config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get 'profiles', to: 'users/registrations#new_profile'
    post 'profiles', to: 'users/registrations#create_profile'
  end
  root "home#index"
  resources :users, only: [:show, :edit, :update]
  resources :profiles, only: [:edit, :update]
  resources :posts do
    resources :comments, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @posts = Post.includes(:user).order('created_at DESC').limit(5)
  end
end

app/views/home/_header.html.haml
.header-wrapper
  .Header
    %h1.Header__title
      =link_to "relief", root_path
    
    .Header__items
      - if user_signed_in?
        %p
          = link_to "マイページ", user_path(current_user.id)
        %p
          = link_to "ログアウト", destroy_user_session_path, method: :delete
        %p
          = link_to edit_user_path(current_user) do
            = current_user.profile.nickname
            = icon('fas', 'cog')
      - else
        %p
          = link_to "新規登録", new_user_registration_path
        %p
          = link_to "ログイン", new_user_session_path

app/views/home/_notifications.html.haml
.Notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/home/index.html.haml
= render "header"
= render "notifications"
.top-wrapper
  .Post-btn
    = link_to new_post_path, class: "Post-btn__link" do
      .Post-btn__items
        %p.Post-btn__items--text
          投稿する
        = icon('fas', 'plus', class: 'Post-btn__items--icon')

  .hero-wrapper
    .Hero
      %p.Hero__main-message
        もう1人で悩まないで
      %p.Hero__message
        今の悩みを共有してみましょう
      %p.Hero__message.Hero__message--large
        意外と簡単に解決するかもしれません
  
  .main-wrapper
    .Post-index-btn
      = link_to posts_path, class: "Post-index-btn__link" do
        %p.Post-index-btn__text
          投 稿 一 覧 へ
    
    .post-wrapper
      %h2 最 新 投 稿
      .post-holder
        = render partial: "posts/post", collection: @posts