config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get 'profiles', to: 'users/registrations#new_profile'
    post 'profiles', to: 'users/registrations#create_profile'
  end
  root "home#index"
  resources :users, only: [:show, :edit, :update]
  resources :profiles, only: [:edit, :update]
  resources :posts do
    resources :comments, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user

  validates :content, presence: true
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :login_required, except: [:index, :show]
  before_action :ensure_correct_user, only: [:edit, :update, :destroy]

  def index
    @posts = Post.includes(:user).order('created_at DESC')
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to root_path, notice: "投稿が完了しました"
    else
      render :new
    end
  end

  def show
    @like = Like.new
    @comment = Comment.new
    @comments = @post.comments.includes(:user)
  end

  def edit
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to root_path, notice: '投稿を更新しました'
    else
      render :edit
    end
  end

  def destroy
    if @post.destroy 
      redirect_to root_path, notice: "投稿の削除が完了しました"
    else
      redirect_to root_path, alert: "権限がありません"
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :content).merge(user_id: current_user.id)
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def login_required
    unless user_signed_in?
      redirect_to root_path, alert: "ログインしてください"
    end
  end

  def ensure_correct_user
    if @post.user_id != current_user.id
      redirect_to root_path, alert: '権限がありません'
    end
  end
end

app/views/posts/_comment_form.html.haml
.comment-wrapper
  - if current_user
    .Comment-form
      = form_with model: [@post, @comment], local: true  do |f|
        .Comment-form__field
          = f.text_area :content, placeholder: "コメントする", class: "Comment-form__area"
        .Comment-form__field
          = f.submit "送 信", class: "Comment-form__submit"
  - else
    %p.comment-warning
      コメントの投稿には新規登録/ログインが必要です
  .comment-index-wrapper
    .Comment-title
      %h4.Comment-title__text
        コメント
      - if @comments
        %p.Comment-title__number
          = @comments.count
          件
      - else
        %p.Comment-title__number
          0件
    .comment-list
      - if @comments
        - @comments.each do |comment|
          .Comment-item
            %p.Comment-item__name
              = link_to comment.user.profile.nickname, "/users/#{comment.user_id}"
            %p.Comment-item__text
              = comment.content
            - if user_signed_in? && current_user.id == comment.user_id
              %p.Comment-item__delete
                = link_to post_comment_path(comment.post.id, comment.id), method: :delete do
                  = icon('fas', 'times')

app/views/posts/_form.html.haml
.post-input-field
  = form_with model: @post, local: true do |f|
    - if @post.errors.any?
      .post-errors
        %ul
          - @post.errors.full_messages.each do |post|
            %li= post
    .post-form-field
      .Post-form
        .Post-form__label タイトル
        = f.text_field :title, class: "Post-form__input"
      .Post-form
        .Post-form__label 本文
        = f.text_area :content, class: "Post-form__area"
    .Post-form-submit
      = f.submit "投稿する", class: "Post-form-submit__btn"

app/views/posts/_post.html.haml
= link_to post_path(post.id) do
  .Post-item
    .Post-prof
      .Post-prof__name
        = post.user.profile.nickname
      .Post-prof__time
        = post.created_at.strftime("%Y/%m/%d %H:%M")
    .Post-item__title
      = post.title
    .Post-item__text
      = post.content
    .Post-item__empathy-count
      %p
        = post.liked_users.count
        %span
          人が共感しています

app/views/posts/edit.html.haml
= render "home/header"
.post-form-wrapper
  %h1 投稿編集
  = render "form"

app/views/posts/index.html.haml
= render 'home/header'

.post-wrapper
  %h2 投 稿 一 覧
  .post-holder
    = render @posts

app/views/posts/new.html.haml
= render "home/header"
.post-new-form-wrapper
  .post-new-form
    %h1 今のお悩みを入力してください
    = form_with model: @post, local: true do |f|
      - if @post.errors.any?
        .post-errors
          %ul
            - @post.errors.full_messages.each do |post|
              %li= post
      .post-form-field
        .Post-form
          .Post-form__label タイトル
          = f.text_field :title, class: "Post-form__input"
        .Post-form
          .Post-form__label 本文
          = f.text_area :content, class: "Post-form__area"
      .Post-form-submit
        = f.submit "投稿する", class: "Post-form-submit__btn"

app/views/posts/show.html.haml
= render "home/header"
.post-show-wrapper
  .post-show-holder
    .Post-item
      - if user_signed_in? && current_user.id == @post.user_id
        .post-btn-list
          .Post-btn
            = link_to edit_post_path(@post), class: "Post-btn__link" do
              %p.Post-btn__text 編集
          .Post-btn
            = link_to post_path(@post), method: :delete, data: {confirm: "削除しますか"}, class: "Post-btn__link" do
              %p.Post-btn__text 削除
      .Post-prof
        .Post-prof__name
          = link_to user_path(@post.user.id) do
            = @post.user.profile.nickname
        .Post-prof__time
          = @post.created_at.strftime("%Y/%m/%d %H:%M")
      .Post-item__title
        = @post.title
      .Post-item__text
        = @post.content     
      .like{id: "like_#{@post.id}"}
        = render partial: "likes/like", locals: { post: @post }
  = render "comment_form"